name: 'Cowsays'
description: 'Say things with a cow'
author: 'Mike Coutermarsh'
inputs:
  text:
    description: 'What does the cow say?'
    default: 'Ship it!!!!!'
  color:
    description: 'Color of your cow'
    default: 'white'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: blue
  icon: message-circle
